# Generated by Django 4.0.5 on 2022-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_bookingid_review_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
