# Generated by Django 4.0.5 on 2022-06-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='bookingId',
            new_name='bookId',
        ),
    ]
